spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BioStudiesDev
    username: root
    password: admin

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

exporter:
  filePath: C:\Users\jhoan\EBI\studies\
